// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GoBook/interactive/events"
	"GoBook/interactive/grpc"
	"GoBook/interactive/ioc"
	"GoBook/interactive/repository"
	"GoBook/interactive/repository/cache"
	"GoBook/interactive/repository/dao"
	"GoBook/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitApp 装配可独立运行的互动微服务。
func InitApp() *App {
	db := ioc.InitDB()
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServer(interactiveServiceServer)
	client := ioc.InitSaramaClient()
	loggerV1 := ioc.InitLogger()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(interactiveRepository, client, loggerV1)
	v := ioc.InitConsumers(interactiveReadEventConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

// thirdProviderSet 汇总数据库、缓存、日志和 Kafka 等基础设施依赖。
var thirdProviderSet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitSaramaClient)

// interactiveProviderSet 描述互动业务从 DAO 到 Service 的依赖链。
var interactiveProviderSet = wire.NewSet(cache.NewRedisInteractiveCache, dao.NewInteractiveDAO, repository.NewInteractiveRepository, service.NewInteractiveService)
