// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"GoBook/interactive/grpc"
	"GoBook/interactive/repository"
	"GoBook/interactive/repository/cache"
	"GoBook/interactive/repository/dao"
	"GoBook/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitInteractiveService 装配供服务层集成测试使用的互动服务。
func InitInteractiveService() service.InteractiveService {
	db := InitDB()
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	return interactiveService
}

// InitInteractiveGRPCService 装配供 gRPC 适配层集成测试使用的服务端。
func InitInteractiveGRPCService() *grpc.InteractiveServiceServer {
	db := InitDB()
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

// thirdProviderSet 汇总集成测试使用的数据库、Redis 和日志依赖。
var thirdProviderSet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
)

// interactiveProviderSet 描述互动服务的完整业务依赖链。
var interactiveProviderSet = wire.NewSet(cache.NewRedisInteractiveCache, dao.NewInteractiveDAO, repository.NewInteractiveRepository, service.NewInteractiveService)
