// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"GoBook/internal/repository"
	article2 "GoBook/internal/repository/article"
	"GoBook/internal/repository/cache"
	"GoBook/internal/repository/dao"
	"GoBook/internal/repository/dao/article"
	"GoBook/internal/service"
	"GoBook/internal/web"
	"GoBook/ioc"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	jwtHandler := NewRedisJWTHandler(cmdable)
	loggerV1 := InitLogger()
	v := ioc.InitMiddleware(cmdable, jwtHandler, loggerV1)
	db := InitDB()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, loggerV1)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, cmdable, jwtHandler, loggerV1)
	wechatService := InitOAuth2WechatService(loggerV1)
	wechatHandlerConfig := NewOAuth2WechatConfig()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, wechatHandlerConfig, jwtHandler)
	articleDAO := article.NewArticleDAO(db)
	authorDAO := article.NewAuthorDAO(db)
	readerDAO := article.NewReaderDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := article2.NewArticleRepository(articleDAO, authorDAO, readerDAO, articleCache, loggerV1)
	producer := InitArticleProducer()
	articleService := service.NewArticleService(articleRepository, producer, loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	articleHandler := web.NewArticleHandler(articleService, loggerV1, interactiveService)
	observerAbilityHandler := web.NewObserverAbilityHandler()
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler, observerAbilityHandler)
	return engine
}

func InitArticleHandler() *web.ArticleHandler {
	db := InitDB()
	articleDAO := article.NewArticleDAO(db)
	authorDAO := article.NewAuthorDAO(db)
	readerDAO := article.NewReaderDAO(db)
	cmdable := InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	loggerV1 := InitLogger()
	articleRepository := article2.NewArticleRepository(articleDAO, authorDAO, readerDAO, articleCache, loggerV1)
	producer := InitArticleProducer()
	articleService := service.NewArticleService(articleRepository, producer, loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	articleHandler := web.NewArticleHandler(articleService, loggerV1, interactiveService)
	return articleHandler
}

// wire.go:

var thirdProviderSet = wire.NewSet(InitDB, InitRedis, InitLogger)

var userSvcProviderSet = wire.NewSet(dao.NewUserDAO, cache.NewUserCache, repository.NewUserRepository, service.NewUserService)
