// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"GoBook/api/proto/gen/interactive/v1"
	repository2 "GoBook/interactive/repository"
	cache2 "GoBook/interactive/repository/cache"
	dao2 "GoBook/interactive/repository/dao"
	service2 "GoBook/interactive/service"
	"GoBook/internal/repository"
	article2 "GoBook/internal/repository/article"
	"GoBook/internal/repository/cache"
	"GoBook/internal/repository/dao"
	"GoBook/internal/repository/dao/article"
	"GoBook/internal/service"
	"GoBook/internal/web"
	"GoBook/internal/web/client"
	"GoBook/ioc"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	jwtHandler := NewRedisJWTHandler(cmdable)
	loggerV1 := InitLogger()
	v := ioc.InitMiddleware(cmdable, jwtHandler, loggerV1)
	db := InitDB()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, loggerV1)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, cmdable, jwtHandler, loggerV1)
	wechatService := InitOAuth2WechatService(loggerV1)
	wechatHandlerConfig := NewOAuth2WechatConfig()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, wechatHandlerConfig, jwtHandler)
	articleDAO := article.NewArticleDAO(db)
	authorDAO := article.NewAuthorDAO(db)
	readerDAO := article.NewReaderDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := article2.NewArticleRepository(articleDAO, authorDAO, readerDAO, articleCache, loggerV1)
	producer := InitArticleProducer()
	articleService := service.NewArticleService(articleRepository, producer)
	interactiveDAO := dao2.NewInteractiveDAO(db)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service2.NewInteractiveService(interactiveRepository)
	interactiveServiceAdapter := client.NewInteractiveServiceAdapter(interactiveService)
	articleHandler := web.NewArticleHandler(articleService, loggerV1, interactiveServiceAdapter)
	observerAbilityHandler := web.NewObserverAbilityHandler()
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler, observerAbilityHandler)
	return engine
}

func InitArticleHandler() *web.ArticleHandler {
	db := InitDB()
	articleDAO := article.NewArticleDAO(db)
	authorDAO := article.NewAuthorDAO(db)
	readerDAO := article.NewReaderDAO(db)
	cmdable := InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	loggerV1 := InitLogger()
	articleRepository := article2.NewArticleRepository(articleDAO, authorDAO, readerDAO, articleCache, loggerV1)
	producer := InitArticleProducer()
	articleService := service.NewArticleService(articleRepository, producer)
	interactiveDAO := dao2.NewInteractiveDAO(db)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewInteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service2.NewInteractiveService(interactiveRepository)
	interactiveServiceAdapter := client.NewInteractiveServiceAdapter(interactiveService)
	articleHandler := web.NewArticleHandler(articleService, loggerV1, interactiveServiceAdapter)
	return articleHandler
}

// wire.go:

// 第三方依赖
var thirdProviderSet = wire.NewSet(
	InitDB,
	InitRedis,
	InitLogger,
)

var userSvcProviderSet = wire.NewSet(cache.NewUserCache, dao.NewUserDAO, repository.NewUserRepository, service.NewUserService)

var codeSvcProviderSet = wire.NewSet(cache.NewCodeCache, repository.NewCodeRepository, service.NewCodeService)

var articleSvcProviderSet = wire.NewSet(article.NewArticleDAO, article.NewAuthorDAO, article.NewReaderDAO, cache.NewRedisArticleCache, article2.NewArticleRepository, service.NewArticleService)

var interactiveProviderSet = wire.NewSet(cache2.NewRedisInteractiveCache, dao2.NewInteractiveDAO, repository2.NewInteractiveRepository, service2.NewInteractiveService, client.NewInteractiveServiceAdapter, wire.Bind(new(interactivev1.InteractiveServiceClient), new(*client.InteractiveServiceAdapter)))
